# Generated by Django 3.1.2 on 2020-10-08 15:09

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=20)),
                ('content', models.TextField(unique_for_year=True)),
                ('post_date', models.DateTimeField(blank=True, default=datetime.datetime(2020, 10, 8, 20, 39, 17, 145066))),
                ('writer', models.CharField(default='Dipanshu', max_length=10)),
            ],
        ),
    ]
