# Generated by Django 3.1.2 on 2020-10-08 15:19

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0002_auto_20201008_2046'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='post_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 10, 8, 20, 49, 5, 403263)),
        ),
    ]
